### ISSUE TITLE
download with datedown

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/smap_io#10]
Hey! As is said I looked at the download script from @cpaulik and I couldn't make it work. Because the [v3 data](https://n5eil01u.ecs.nsidc.org/SMAP/SPL3SMP.003/) is not there anymore or it was moved/renamed...
Now I tried to do the download for the[ version 5 data ](https://n5eil01u.ecs.nsidc.org/SMAP/SPL3SMP.005/)and it also failed when using `datedown`. The problem is that the "Minor CRID Version Number" part of the file names changes at some point in time (after 2017-09-05) and also the "Product Counter" changes (so the names not only depend on the dt). So I tried to use the `--recursive` option in datedown/wget, but I only download the `index.html` then, unless I add `-e robots=off` (robots=off is also suggested in the [official instructions](https://nsidc.org/support/how/how-do-i-use-wget-bulk-downloading-data-set)).
But the robots option is not support in `datedown` (i've added it now and the download works fine). So what would you suggest? Do the download without `datedown`, update `datedown`?, hard code the change in the file names (I would not do that), or maybe you have some different solution?

**Comment by sebhahn** [comment]
Would you have to copy functionality from `datedown`?

**Comment by wpreimes** [comment]
You mean if we don't use datedown? Basically the parts that create dates between`--start`and `--end` and replace the datetimes in the URLs (but thats mostly what datedown does, as far as I see it) we would have to copy (or import) and then call wget outside of `datedown`.

**Comment by wpreimes** [comment]
Also eg parallelization is in `datedown`

**Comment by sebhahn** [comment]
And do you think an extension of `datedown` makes sense, or is this download too special to be implemented in `datedown`?

**Comment by wpreimes** [comment]
I haven't worked enough with wget to assess this ;) But maybe it would make sense to add an option to `datedown` to force some parameters that are not explicitly used in the [download](https://github.com/cpaulik/datedown/blob/bdf249b18dcd48826a0eedc7d9b7affae5eabc56/datedown/wget.py#L31) yet (like `-e` in our case), but I don't know how restrictive `datedown` should be. As far as I have read now, robots=off may go around restrictions that the server provider has set (?) (which is bad, and I would not use it if it wasn't written in the official guide)

**Comment by sebhahn** [comment]
Ok create a PR and we can have a look at it

**Comment by wpreimes** [comment]
Download module is part of the master now
